name: nearest_cityV2
channels:
  - defaults
dependencies:
  - click=8.1.3
  - flask=2.2.2
  - geographiclib=1.52
  - geopy=2.2.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - markupsafe=2.1.1
  - numpy=1.23.3
  - pip=22.2.2
  - pyshp=2.3.1
  - pytest=7.1.3
  - python=3.10.6
  - reverse_geocoder=1.5.1
  - scipy=1.9.1
  - setuptools=65.4.1
  - werkzeug=2.2.2
  - wheel=0.37.1
